db:
  image: postgres
  ports:
    - "5432"

web:
  image: jdabbs/strife_web
  env_file: ./prod.env
  command: bundle exec rails s -p 3000 -b "0.0.0.0"
  ports:
    - "3000:3000"
  links:
    - db

slackbot:
  image: jdabbs/strife_web
  env_file: ./prod.env
  command: bundle exec rails runner bin/slackbot.rb
  links:
    - db
